# Database connection setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coremicro
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  file:
    name: C:/logs/coremicro.log
    encoding: UTF-8
  level:
    org:
      hibernate:
        sql: info

server:
  port: 5000
#
#
#
# It can be used application.properties insteed ###############################
# spring.datasource.url=jdbc:mysql://localhost:3306/mya                       #
# spring.datasource.username=root                                             #
# spring.datasource.password=1234                                             #
#                                                                             #
# spring.jpa.show-sql=true                                                    #
# spring.jpa.hibernate.ddl-auto=update                                        #
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect #
#                                                                             #
# spring.main.allow-bean-definition-overriding=true                           #
#                                                                             #
# server.port=5000                                                            #
#                                                                             #
# logging.file.name=C:/logs/myapp.log                                         #
# logging.file.encoding=UTF-8                                                 #
#                                                                             #
#Thymeleaf                                                                    #
# spring.thymeleaf.cache=false                                                #
# spring.thymeleaf.suffix: .html                                              #
###############################################################################
