# Database connection setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  file:
    name: C:/logs/order-service.log
    encoding: UTF-8
  level:
    org:
      hibernate:
        sql: info

server:
  port: 5002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5004/eureka
  instance:
    appname: order-service
