# Database connection setting
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  file:
    name: C:/logs/discovery-server.log
    encoding: UTF-8
  level:
    org:
      hibernate:
        sql: info

server:
  port: 5004
  # EUREKA
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
